namespace DataReader.ExternalAPI.Properties
{
  public static class WorkItemsColumnsList
  {
    public static List<string> columns = new List<string>() {
        { new string("WorkItemId") },
        { new string("InProgressDate") },
        { new string("CompletedDate") },
        { new string("InProgressDateSK") },
        { new string("CompletedDateSK") },
        { new string("AnalyticsUpdatedDate") },
        { new string("ProjectSK") },
        { new string("WorkItemRevisionSK") },
        { new string("AreaSK") },
        { new string("IterationSK") },
        { new string("AssignedToUserSK") },
        { new string("ChangedByUserSK") },
        { new string("CreatedByUserSK") },
        { new string("ActivatedByUserSK") },
        { new string("ClosedByUserSK") },
        { new string("ResolvedByUserSK") },
        { new string("ActivatedDateSK") },
        { new string("ChangedDateSK") },
        { new string("ClosedDateSK") },
        { new string("CreatedDateSK") },
        { new string("ResolvedDateSK") },
        { new string("StateChangeDateSK") },
        { new string("WorkItemType") },
        { new string("ChangedDate") },
        { new string("CreatedDate") },
        { new string("State") },
        { new string("ActivatedDate") },
        { new string("ClosedDate") },
        { new string("Priority") },
        { new string("ResolvedDate") },
        { new string("CompletedWork") },
        { new string("Effort") },
        { new string("FinishDate") },
        { new string("OriginalEstimate") },
        { new string("RemainingWork") },
        { new string("StartDate") },
        { new string("StoryPoints") },
        { new string("TargetDate") },
        { new string("ParentWorkItemId") },
        { new string("TagNames") },
        { new string("StateChangeDate") },
        { new string("Custom_719f69f1__002Df7d0__002D4baa__002Db6ce__002De77ad5dfcdf3") },
        { new string("Custom_Company") },
        { new string("Custom_Eksternareferenca") },
        { new string("Custom_ITServiceorApplication") },
        { new string("Custom_Statusprojekta") },
        { new string("Custom_TicketNo") }
      };
  }
}
